version: '3.4'

networks:
  frontend:
  backend:

services:
  catalog:
    image: events/catalogapi
    build:
      context: .\EventCatalogApi
      dockerfile: Dockerfile
    environment:
      DatabaseServer: mssqlserver
      DatabaseName: Catalog2Db
      DatabaseUser: ev
      DatabasePassword: EventApi(!)
      ExternalCatalogBaseUrl: http://localhost:6600
    ports:
      - "6600:80"
    container_name: Eventscatalogapi
    networks:
      - backend
      - frontend
    depends_on:
      - mssqlserver

  mssqlserver:
    image: "microsoft/mssql-server-linux:latest"
    environment:
      ACCEPT_EULA: Y
      EV_PASSWORD: EventApi(!)
    ports: 
      - "1445:1433"
    container_name: eventssqlserver
    networks: 
      - backend
