version: '3.4'

networks:
  frontend:
  backend:

services:
  catalog:
    image: events/catalogapi
    build:
      context: .\EventCatalogApi
      dockerfile: Dockerfile
    environment:
      DatabaseServer: mssqlserver
      DatabaseName: Catalog2Db
      DatabaseUser: ev
      DatabasePassword: EventApi(!)
      ExternalCatalogBaseUrl: http://localhost:51858

