version: '3.4'

networks:
  frontend:
  backend:

services:
  catalog:
    image: events/catalogapi
    build:
      context: .\EventCatalogApi
      dockerfile: Dockerfile
    environment:
      DatabaseServer: mssqlserver
      DatabaseName: Catalog2Db
      DatabaseUser: sa
      DatabasePassword: EventApi(!)
      ExternalCatalogBaseUrl: http://localhost:6400
    ports:
      - "6400:80"
    container_name: Eventscatalogapi
    networks:
      - backend
      - frontend
    depends_on:
      - mssqlserver

  cart:
    build:
      context: .\CartApi
      dockerfile: Dockerfile
    image: events/cartapi
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      IdentityUrl: http://192.168.1.4:6500
      ConnectionString: basket.data
    ports:
      - "6501:80"
    container_name: cartapi
    networks:
      - backend
      - frontend
    depends_on:
      - basket.data
      - tokenserver
      - rabbitmq

  order:
    build:
      context: .\OrderApi
      dockerfile: Dockerfile
    image: events/orderapi
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      IdentityUrl: http://192.168.1.4:6500
      DatabaseServer: mssqlserver
      DatabaseName: Catalog2Db
      DatabaseUser: sa
      DatabasePassword: EventApi(!)
    ports:
      - "6502:80"
    container_name: orderapi
    networks:
      - backend
      - frontend
    depends_on:
      - mssqlserver
      - tokenserver
      - rabbitmq


  mssqlserver:
    image: "microsoft/mssql-server-linux:latest"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: EventApi(!)
    ports: 
      - "1440:1433"
    container_name: eventssqlserver
    networks: 
      - backend

  tokenserver:
    build:
      context: .\TokenServiceApi
      dockerfile: Dockerfile
    image: events/tokenapi
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      MvcClient: http://localhost:5200
      BasketApiClient: https://localhost:6501
    ports:
      - "6500:80"
    container_name: tokenserviceapi
    networks:
      - backend
      - frontend
    depends_on:
      - mssqlserver

  webmvc:
    build:
      context: .\webmvc
      dockerfile: Dockerfile
    image: events/webmvc
    container_name: webshop
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      CatalogUrl: http://catalog
      IdentityUrl: http://192.168.1.4:6500
      CallBackUrl: http://localhost:5200
      CartUrl: http://cart
      OrderUrl: http://order
      StripePublicKey: pk_test_hK9OkXdGyGGGRuMP3YX8duaJ00sBicbPlN
      StripePrivateKey: sk_test_06ecM0oA2j0njgKNjyNdWkAC00reGIxwe0
    ports:
      - "5200:80"
    networks:
      - frontend
    depends_on:
      - catalog
      - cart
      - order
      - tokenserver


  basket.data:
    image: redis
    container_name: basketdata
    ports:
      - "6090:6379"
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: myrabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
      - "5671:5671"
    volumes:
      - ~/rabbitmq:/var/lib/rabbitmq/mnesia   
    networks:
      - backend 
